import type { Metadata } from "next";
import "./globals.css";
import { Lato } from "next/font/google";
import Footer from "@/components/footer";

const lato = Lato({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-lato",
});


export const metadata: Metadata = {
  title: "pokedex",
  description: "Generated by Allysa",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lato.variable} antialiased`}>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
